
public enum EventType {

    ARRIVAL_AT_GASSTATION,
    END_OF_WASHING_ONLY,
    END_OF_REFUELING_FUEL_ONLY,
    END_OF_REFUELING_WASHING_AND_REFUELING,
    END_OF_PAYMENT_FUEL_ONLY,
    END_OF_PAYMENT_WASHING_ONLY,
    END_OF_PAYMENT_WASHING_AND_REFUELING;

}
